last_build_profile = "adl_middleware=RELEASE,cortex_m=RELEASE,embedded_components=RELEASE,gnat_arm_elf=RELEASE,gps=DEVELOPMENT,hal=RELEASE,stm32_gui=RELEASE,stm32_hal=RELEASE,stm32f429disco=RELEASE"

