name = "ir_motion"
description = ""
version = "0.1.0-dev"

authors = ["Karamoko"]
maintainers = ["Karamoko <kara.2002@hotmail.fr>"]
maintainers-logins = ["Karamoko27"]
licenses = "MIT OR Apache-2.0 WITH LLVM-exception"
website = ""
tags = []

executables = ["ir_motion"]

[[depends-on]]
stm32f429disco = "~0.1.0"

[[depends-on]]
stm32_gui = "~0.1.0"

[[pins]]
gnat_arm_elf = { version='12.2.1' }
