name = "target_serial"
description = ""
version = "0.1.0-dev"

authors = ["Bass"]
maintainers = ["Bass <btour069@uottawa.ca>"]
maintainers-logins = ["Bass069"]
licenses = "MIT OR Apache-2.0 WITH LLVM-exception"
website = ""
tags = []

executables = ["target_serial"]

[[depends-on]]
stm32f429disco = "0.1.0"

